spring.application.name=library-management

spring.datasource.url=jdbc:postgresql://localhost:5432/library_dev
spring.datasource.username=postgres
spring.datasource.password=intern@cdot
spring.jpa.hibernate.ddl-auto=validate



server.port=8080

spring.security.user.name=library
spring.security.user.password=library


jwt.secret=cdot@library#2024$management!secret%key&secure
jwt.expiration=86400000




spring.mail.host=smtp.mgovcloud.in
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true

spring.mail.username=cdot.interns@cdot.in
spring.mail.password=JBUELskAVwDy
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=2000
spring.mail.properties.mail.smtp.timeout=2000
spring.mail.properties.mail.smtp.writetimeout=2000